name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
      with:
        path: cdk-ci
    - uses: actions/checkout@v3
      with:
        repository: "cashubtc/cdk"
        path: "cdk"
    - name: Copy flakes
      working-directory: cdk
      run: |
        cp flake.nix ../cdk-ci/flake.nix
        cp flake.lock ../cdk-ci/flake.lock
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: cdk-ci
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
